/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedNearbyRouteImport } from './routes/_authenticated/nearby'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedGameRouteImport } from './routes/_authenticated/game'
import { Route as AuthenticatedMeIndexRouteImport } from './routes/_authenticated/me.index'
import { Route as AuthenticatedGameIndexRouteImport } from './routes/_authenticated/game.index'
import { Route as AuthenticatedMeOffersRouteImport } from './routes/_authenticated/me.offers'
import { Route as AuthenticatedMeLeavesRouteImport } from './routes/_authenticated/me.leaves'
import { Route as AuthenticatedMeItemsRouteImport } from './routes/_authenticated/me.items'
import { Route as AuthenticatedGameMatchesRouteImport } from './routes/_authenticated/game.matches'
import { Route as AuthenticatedChatOfferIdRouteImport } from './routes/_authenticated/chat.$offerId'
import { Route as AuthenticatedMeItemsIndexRouteImport } from './routes/_authenticated/me.items.index'
import { Route as AuthenticatedSwapsOfferIdReviewRouteImport } from './routes/_authenticated/swaps.$offerId.review'
import { Route as AuthenticatedMeItemsNewRouteImport } from './routes/_authenticated/me.items.new'
import { Route as AuthenticatedGamePlayItemIdRouteImport } from './routes/_authenticated/game.play.$itemId'
import { Route as AuthenticatedMeItemsIdEditRouteImport } from './routes/_authenticated/me.items.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNearbyRoute = AuthenticatedNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGameRoute = AuthenticatedGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeIndexRoute = AuthenticatedMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedGameIndexRoute = AuthenticatedGameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGameRoute,
} as any)
const AuthenticatedMeOffersRoute = AuthenticatedMeOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedMeLeavesRoute = AuthenticatedMeLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedMeItemsRoute = AuthenticatedMeItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedGameMatchesRoute =
  AuthenticatedGameMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedGameRoute,
  } as any)
const AuthenticatedChatOfferIdRoute =
  AuthenticatedChatOfferIdRouteImport.update({
    id: '/chat/$offerId',
    path: '/chat/$offerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeItemsIndexRoute =
  AuthenticatedMeItemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMeItemsRoute,
  } as any)
const AuthenticatedSwapsOfferIdReviewRoute =
  AuthenticatedSwapsOfferIdReviewRouteImport.update({
    id: '/swaps/$offerId/review',
    path: '/swaps/$offerId/review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeItemsNewRoute = AuthenticatedMeItemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedMeItemsRoute,
} as any)
const AuthenticatedGamePlayItemIdRoute =
  AuthenticatedGamePlayItemIdRouteImport.update({
    id: '/play/$itemId',
    path: '/play/$itemId',
    getParentRoute: () => AuthenticatedGameRoute,
  } as any)
const AuthenticatedMeItemsIdEditRoute =
  AuthenticatedMeItemsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedMeItemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/game': typeof AuthenticatedGameRouteWithChildren
  '/me': typeof AuthenticatedMeRouteWithChildren
  '/nearby': typeof AuthenticatedNearbyRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/items/$id': typeof ItemsIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/chat/$offerId': typeof AuthenticatedChatOfferIdRoute
  '/game/matches': typeof AuthenticatedGameMatchesRoute
  '/me/items': typeof AuthenticatedMeItemsRouteWithChildren
  '/me/leaves': typeof AuthenticatedMeLeavesRoute
  '/me/offers': typeof AuthenticatedMeOffersRoute
  '/game/': typeof AuthenticatedGameIndexRoute
  '/me/': typeof AuthenticatedMeIndexRoute
  '/game/play/$itemId': typeof AuthenticatedGamePlayItemIdRoute
  '/me/items/new': typeof AuthenticatedMeItemsNewRoute
  '/swaps/$offerId/review': typeof AuthenticatedSwapsOfferIdReviewRoute
  '/me/items/': typeof AuthenticatedMeItemsIndexRoute
  '/me/items/$id/edit': typeof AuthenticatedMeItemsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/items/$id': typeof ItemsIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/chat/$offerId': typeof AuthenticatedChatOfferIdRoute
  '/game/matches': typeof AuthenticatedGameMatchesRoute
  '/me/leaves': typeof AuthenticatedMeLeavesRoute
  '/me/offers': typeof AuthenticatedMeOffersRoute
  '/game': typeof AuthenticatedGameIndexRoute
  '/me': typeof AuthenticatedMeIndexRoute
  '/game/play/$itemId': typeof AuthenticatedGamePlayItemIdRoute
  '/me/items/new': typeof AuthenticatedMeItemsNewRoute
  '/swaps/$offerId/review': typeof AuthenticatedSwapsOfferIdReviewRoute
  '/me/items': typeof AuthenticatedMeItemsIndexRoute
  '/me/items/$id/edit': typeof AuthenticatedMeItemsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/game': typeof AuthenticatedGameRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRouteWithChildren
  '/_authenticated/nearby': typeof AuthenticatedNearbyRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/items/$id': typeof ItemsIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/_authenticated/chat/$offerId': typeof AuthenticatedChatOfferIdRoute
  '/_authenticated/game/matches': typeof AuthenticatedGameMatchesRoute
  '/_authenticated/me/items': typeof AuthenticatedMeItemsRouteWithChildren
  '/_authenticated/me/leaves': typeof AuthenticatedMeLeavesRoute
  '/_authenticated/me/offers': typeof AuthenticatedMeOffersRoute
  '/_authenticated/game/': typeof AuthenticatedGameIndexRoute
  '/_authenticated/me/': typeof AuthenticatedMeIndexRoute
  '/_authenticated/game/play/$itemId': typeof AuthenticatedGamePlayItemIdRoute
  '/_authenticated/me/items/new': typeof AuthenticatedMeItemsNewRoute
  '/_authenticated/swaps/$offerId/review': typeof AuthenticatedSwapsOfferIdReviewRoute
  '/_authenticated/me/items/': typeof AuthenticatedMeItemsIndexRoute
  '/_authenticated/me/items/$id/edit': typeof AuthenticatedMeItemsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/home'
    | '/login'
    | '/signup'
    | '/game'
    | '/me'
    | '/nearby'
    | '/verify'
    | '/items/$id'
    | '/profile/$userId'
    | '/chat/$offerId'
    | '/game/matches'
    | '/me/items'
    | '/me/leaves'
    | '/me/offers'
    | '/game/'
    | '/me/'
    | '/game/play/$itemId'
    | '/me/items/new'
    | '/swaps/$offerId/review'
    | '/me/items/'
    | '/me/items/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/home'
    | '/login'
    | '/signup'
    | '/nearby'
    | '/verify'
    | '/items/$id'
    | '/profile/$userId'
    | '/chat/$offerId'
    | '/game/matches'
    | '/me/leaves'
    | '/me/offers'
    | '/game'
    | '/me'
    | '/game/play/$itemId'
    | '/me/items/new'
    | '/swaps/$offerId/review'
    | '/me/items'
    | '/me/items/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/browse'
    | '/home'
    | '/login'
    | '/signup'
    | '/_authenticated/game'
    | '/_authenticated/me'
    | '/_authenticated/nearby'
    | '/_authenticated/verify'
    | '/items/$id'
    | '/profile/$userId'
    | '/_authenticated/chat/$offerId'
    | '/_authenticated/game/matches'
    | '/_authenticated/me/items'
    | '/_authenticated/me/leaves'
    | '/_authenticated/me/offers'
    | '/_authenticated/game/'
    | '/_authenticated/me/'
    | '/_authenticated/game/play/$itemId'
    | '/_authenticated/me/items/new'
    | '/_authenticated/swaps/$offerId/review'
    | '/_authenticated/me/items/'
    | '/_authenticated/me/items/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ItemsIdRoute: typeof ItemsIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nearby': {
      id: '/_authenticated/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AuthenticatedNearbyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/game': {
      id: '/_authenticated/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AuthenticatedGameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/': {
      id: '/_authenticated/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthenticatedMeIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/game/': {
      id: '/_authenticated/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof AuthenticatedGameIndexRouteImport
      parentRoute: typeof AuthenticatedGameRoute
    }
    '/_authenticated/me/offers': {
      id: '/_authenticated/me/offers'
      path: '/offers'
      fullPath: '/me/offers'
      preLoaderRoute: typeof AuthenticatedMeOffersRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/leaves': {
      id: '/_authenticated/me/leaves'
      path: '/leaves'
      fullPath: '/me/leaves'
      preLoaderRoute: typeof AuthenticatedMeLeavesRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/items': {
      id: '/_authenticated/me/items'
      path: '/items'
      fullPath: '/me/items'
      preLoaderRoute: typeof AuthenticatedMeItemsRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/game/matches': {
      id: '/_authenticated/game/matches'
      path: '/matches'
      fullPath: '/game/matches'
      preLoaderRoute: typeof AuthenticatedGameMatchesRouteImport
      parentRoute: typeof AuthenticatedGameRoute
    }
    '/_authenticated/chat/$offerId': {
      id: '/_authenticated/chat/$offerId'
      path: '/chat/$offerId'
      fullPath: '/chat/$offerId'
      preLoaderRoute: typeof AuthenticatedChatOfferIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/items/': {
      id: '/_authenticated/me/items/'
      path: '/'
      fullPath: '/me/items/'
      preLoaderRoute: typeof AuthenticatedMeItemsIndexRouteImport
      parentRoute: typeof AuthenticatedMeItemsRoute
    }
    '/_authenticated/swaps/$offerId/review': {
      id: '/_authenticated/swaps/$offerId/review'
      path: '/swaps/$offerId/review'
      fullPath: '/swaps/$offerId/review'
      preLoaderRoute: typeof AuthenticatedSwapsOfferIdReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/items/new': {
      id: '/_authenticated/me/items/new'
      path: '/new'
      fullPath: '/me/items/new'
      preLoaderRoute: typeof AuthenticatedMeItemsNewRouteImport
      parentRoute: typeof AuthenticatedMeItemsRoute
    }
    '/_authenticated/game/play/$itemId': {
      id: '/_authenticated/game/play/$itemId'
      path: '/play/$itemId'
      fullPath: '/game/play/$itemId'
      preLoaderRoute: typeof AuthenticatedGamePlayItemIdRouteImport
      parentRoute: typeof AuthenticatedGameRoute
    }
    '/_authenticated/me/items/$id/edit': {
      id: '/_authenticated/me/items/$id/edit'
      path: '/$id/edit'
      fullPath: '/me/items/$id/edit'
      preLoaderRoute: typeof AuthenticatedMeItemsIdEditRouteImport
      parentRoute: typeof AuthenticatedMeItemsRoute
    }
  }
}

interface AuthenticatedGameRouteChildren {
  AuthenticatedGameMatchesRoute: typeof AuthenticatedGameMatchesRoute
  AuthenticatedGameIndexRoute: typeof AuthenticatedGameIndexRoute
  AuthenticatedGamePlayItemIdRoute: typeof AuthenticatedGamePlayItemIdRoute
}

const AuthenticatedGameRouteChildren: AuthenticatedGameRouteChildren = {
  AuthenticatedGameMatchesRoute: AuthenticatedGameMatchesRoute,
  AuthenticatedGameIndexRoute: AuthenticatedGameIndexRoute,
  AuthenticatedGamePlayItemIdRoute: AuthenticatedGamePlayItemIdRoute,
}

const AuthenticatedGameRouteWithChildren =
  AuthenticatedGameRoute._addFileChildren(AuthenticatedGameRouteChildren)

interface AuthenticatedMeItemsRouteChildren {
  AuthenticatedMeItemsNewRoute: typeof AuthenticatedMeItemsNewRoute
  AuthenticatedMeItemsIndexRoute: typeof AuthenticatedMeItemsIndexRoute
  AuthenticatedMeItemsIdEditRoute: typeof AuthenticatedMeItemsIdEditRoute
}

const AuthenticatedMeItemsRouteChildren: AuthenticatedMeItemsRouteChildren = {
  AuthenticatedMeItemsNewRoute: AuthenticatedMeItemsNewRoute,
  AuthenticatedMeItemsIndexRoute: AuthenticatedMeItemsIndexRoute,
  AuthenticatedMeItemsIdEditRoute: AuthenticatedMeItemsIdEditRoute,
}

const AuthenticatedMeItemsRouteWithChildren =
  AuthenticatedMeItemsRoute._addFileChildren(AuthenticatedMeItemsRouteChildren)

interface AuthenticatedMeRouteChildren {
  AuthenticatedMeItemsRoute: typeof AuthenticatedMeItemsRouteWithChildren
  AuthenticatedMeLeavesRoute: typeof AuthenticatedMeLeavesRoute
  AuthenticatedMeOffersRoute: typeof AuthenticatedMeOffersRoute
  AuthenticatedMeIndexRoute: typeof AuthenticatedMeIndexRoute
}

const AuthenticatedMeRouteChildren: AuthenticatedMeRouteChildren = {
  AuthenticatedMeItemsRoute: AuthenticatedMeItemsRouteWithChildren,
  AuthenticatedMeLeavesRoute: AuthenticatedMeLeavesRoute,
  AuthenticatedMeOffersRoute: AuthenticatedMeOffersRoute,
  AuthenticatedMeIndexRoute: AuthenticatedMeIndexRoute,
}

const AuthenticatedMeRouteWithChildren = AuthenticatedMeRoute._addFileChildren(
  AuthenticatedMeRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedGameRoute: typeof AuthenticatedGameRouteWithChildren
  AuthenticatedMeRoute: typeof AuthenticatedMeRouteWithChildren
  AuthenticatedNearbyRoute: typeof AuthenticatedNearbyRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedChatOfferIdRoute: typeof AuthenticatedChatOfferIdRoute
  AuthenticatedSwapsOfferIdReviewRoute: typeof AuthenticatedSwapsOfferIdReviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGameRoute: AuthenticatedGameRouteWithChildren,
  AuthenticatedMeRoute: AuthenticatedMeRouteWithChildren,
  AuthenticatedNearbyRoute: AuthenticatedNearbyRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
  AuthenticatedChatOfferIdRoute: AuthenticatedChatOfferIdRoute,
  AuthenticatedSwapsOfferIdReviewRoute: AuthenticatedSwapsOfferIdReviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ItemsIdRoute: ItemsIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
